codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 100%
        base: auto
        if_ci_failed: success
        informational: true
    patch:
      default:
        target: auto
        threshold: 100%
        base: auto
        if_ci_failed: success
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_head: no
  require_base: no

github_checks:
  annotations: false
