file(READ "${SHEENBIDI_DIR}/CMakeLists.txt" SHEENBIDI_CMAKELISTS_CONTENTS)
string(REGEX REPLACE "include\\(GNUInstallDirs\\).*" "" SHEENBIDI_CMAKELISTS_CONTENTS "${SHEENBIDI_CMAKELISTS_CONTENTS}")
string(REPLACE "add_library(SheenBidi\n" "add_library(SheenBidi OBJECT\n" SHEENBIDI_CMAKELISTS_CONTENTS "${SHEENBIDI_CMAKELISTS_CONTENTS}")
file(WRITE "${SHEENBIDI_DIR}/CMakeLists.txt" "${SHEENBIDI_CMAKELISTS_CONTENTS}")
